### ISSUE TITLE
Text-based adventure workshop

### ISSUE THREAD

**Issue by aepsil0n** [rust-community/rustbridge#13]
@wycats is working on [this](https://github.com/tildeio/learning-rust)

**Comment by fvasquez** [comment]
We're on this.

http://github.com/neunenak/rustbridge

Contact me or Greg.

**Comment by kainino0x** [comment]
Our CIS 198 course did a text adventure as an assignment last semester. If you wish, please steal content or inspiration: https://github.com/cis198-2016s/homework/tree/master/hw05
(We can provide our solutions as well, but they're not published.)

**Comment by fvasquez** [comment]
Hi Kai,

You're text adventure is very close to what I had in mind for this workshop.  The rules for my game also came from a course homework assignment.  I think I will borrow from what you've done.  Loading the game board from a castle.json file is an excellent idea.

-Frank

**Comment by erickt** [comment]
@fvasquez's work has now been merged into https://github.com/rust-community/rustbridge/tree/master/workshops/textadventure.
