### ISSUE TITLE
2016-07-19 Meeting

### ISSUE THREAD

**Issue by erickt** [rust-community/rustbridge#16]
cc @rust-community/rustbridge

We are considering having this meeting at [4pm UTC](http://everytimezone.com/#2016-7-19,240,cn3) or [5pm UTC](http://everytimezone.com/#2016-7-19,300,cn3). Please vote below on your preference, and add any agenda items.

Action items from [last week](https://github.com/rust-community/rustbridge/issues/8):
- @aepsil0n volunteered to track progress on workshops, and bug all us meetup organizers into actually getting workshop-a-thons happening
- workshop-a-thons!
- move meeting minutes into rustbridge
- check back in 2 weeks when @SonjaHeinen gets back online on web stuff

Upcoming meeting agenda items:
- ???

**Comment by booyaa** [comment]
I'm able to do both 4PM and 5PM.

**Comment by aepsil0n** [comment]
So the meeting did not really take place, because there were so few people. The three of us, who were present realized that nothing much had been done and decided to skip it.
