### ISSUE TITLE
2016-07-26 meeting

### ISSUE THREAD

**Issue by aepsil0n** [rust-community/rustbridge#17]
Let's agree on a time and date earlier this time.

Does 4pm UTC on July 26 work? By default, let's try to stick to this slot for the meeting.

**Comment by erickt** [comment]
@rust-community/rustbridge: ping!

Tomorrow at 4pm UTC works for me!

**Comment by hannelita** [comment]
I'll be online this time!

**Comment by broesamle** [comment]
It will work for me as well 
: )
Martin

**Comment by aepsil0n** [comment]
cool, see you all later then ;)

**Comment by erickt** [comment]
Action items:

* @broesamle will do some research into materials teaching basic info like data structures, pointers, etc.
* @booyaa will investigate a tutorial to prep a machine for [workshops](https://github.com/rust-community/rustbridge/issues/18).
* @hannelita is hosting a workshop-a-thon on 8/3.

**Comment by hannelita** [comment]
Created #20 with a better description
