### ISSUE TITLE
2016-08-02 Meeting

### ISSUE THREAD

**Issue by erickt** [rust-community/rustbridge#19]
@rust-community/rustbridge: Meeting at [4pm UTC](http://everytimezone.com/#2016-3-29,1680,cn3) on #rust-community on irc.mozilla.org. [Last week's agenda](https://github.com/rust-community/rustbridge/issues/17).

Agenda:
- [Tutorial on setting up a machine](https://github.com/rust-community/rustbridge/issues/18)
- Prep work to help @hannelita get ready for the 8/3 workshop-a-thon
- ???

**Comment by hannelita** [comment]
@erickt Just an update- 8/3 is going to be a regular talk, where I plan to show the parser app step by step. It is not going to be a workshop during the Sao Paulo meetup.

**Comment by aepsil0n** [comment]
Just fyi I might come in a little later tonight.

**Comment by broesamle** [comment]
when are we meeting 4 or 5?

**Comment by booyaa** [comment]
@broesamle It was 4PM UTC

**Comment by booyaa** [comment]
Can't editing the main document, but we have a new action 

- @broesamle is offering to help out if anyone needs assistance

**Comment by broesamle** [comment]
presumably reviewing material / testing examples or the like.
