### ISSUE TITLE
Who should be collaborators on this repo?

### ISSUE THREAD

**Issue by carols10cents** [rust-community/rustbridge#3]
Who are people who have expressed interest in working on content and running events? @skade mentioned he knows of at least 5 people, but I'm not sure who they are.

**Comment by skade** [comment]
@carols10cents I'm still waiting for their answer to just put them in touch :).

**Comment by skade** [comment]
@SonjaHeinen showed interest and (as a bonus) currently has time!

**Comment by skade** [comment]
@softprops got in touch over email

**Comment by skade** [comment]
@realtin is a ClojureBridge organiser and Diaspora committer from Berlin, generally interested in many technologies. She'd be interested and being involved.

**Comment by skade** [comment]
@xamebax is from Berlin, Devops expert and is involved in Rails Girls in Berlin and Warsaw from time to time. She'd be interested in helping out, as her time allows.

**Comment by carols10cents** [comment]
I've invited all these folks to the Rustbridge team!

**Comment by skade** [comment]
@broesamle has experiences writing workshop materials, but is a Rust beginner. He'd be happy to help.

Here's an example of work: https://www.freidok.uni-freiburg.de/data/9404

**Comment by skade** [comment]
@hannelita is from Sao Paolo and would be interested in taking part, too. She founded the Rust Meetup there.

**Comment by carols10cents** [comment]
Invited those two!

**Comment by skade** [comment]
And finally @anoukruhaak, who is involved in WomenWhoCode and can provide help and contacts and general experience \o/.

**Comment by hannelita** [comment]
Thanks @carols10cents @skade ! :)

**Comment by carols10cents** [comment]
Added @anoukruhaak!

**Comment by carols10cents** [comment]
Should we publicize this a bit more, i.e. post on twitter/reddit/urlo/twir that we're starting up a team to work on rustbridge/organization? At what point do we get too many cooks in the kitchen?

**Comment by skade** [comment]
I'd like to stop here for now until we have talked to the Bridge Foundry. (hopefully soon...) Then, I'd do general outreach with tasks at hand.

**Comment by skade** [comment]
Given that some time has passed, we should announce this as a formed team.

**Comment by skade** [comment]
I guess we can close this one.
