### ISSUE TITLE
2016-08-23 RustBridge Meeting

### ISSUE THREAD

**Issue by erickt** [rust-community/rustbridge#37]
@rust-community/rustbridge: Meeting at [4pm UTC](http://everytimezone.com/#2016-3-29,1680,cn3) on #rustbridge on irc.mozilla.org. [Last week's agenda](https://github.com/rust-community/rustbridge/issues/19).

Agenda items:

* Website
* [License](https://github.com/rust-community/rustbridge/pull/33)

**Comment by broesamle** [comment]
I'd like to add 
* #38

**Comment by erickt** [comment]
@rust-community/rustbridge: Team meeting in 30 minutes!

**Comment by erickt** [comment]
Summary:

* [Updated license to include CC-BY](https://github.com/rust-community/rustbridge/pull/39)
* [Moving the meeting time?](https://github.com/rust-community/rustbridge/issues/41)
* [Merging the web scraper](https://github.com/rust-community/rustbridge/pull/40)
* rustfest.eu planning to beta test rustbridge
