### ISSUE TITLE
Rustbridge Event at RustFest

### ISSUE THREAD

**Issue by johannhof** [rust-community/rustbridge#38]
@aepsil0n and I had some early plans about doing a Rustbridge workshop at the second day of RustFest in Berlin (www.rustfest.eu).

I'd like to start coordinating this now, the main question is: Will we be ready to perform an actual workshop with newcomers or should we rather do a workshopathon where we work on workshops together?

**Comment by broesamle** [comment]
so, after talking (mailing) back to Ben we will have one room for rustbridge .. he liked the idea of having two workshops with different level of prior knowledge/skills.

We can still decide whether we do them one after the other or whether we give a quick overview on both and then have the learners decide which one to follow

**Comment by broesamle** [comment]
here we go:
http://discourse.opentechschool.org/t/rustbridge-workshop-sept-18th-berlin-together-with-rustfest/1849
