### ISSUE TITLE
Unfortunate name collision with another RustBridge-named project

### ISSUE THREAD

**Issue by erickt** [rust-community/rustbridge#4]
Unfortunately it looks like there's already a [Rust Bridge](https://github.com/rustbridge) project, started by @dherman to use Rust to write bindings for other languages, starting with JavaScript and Ruby. We probably ought to rename this project since that Rust Bridge already has a lot of momentum behind it 😞 and could get confusing if they and we both try to organize "Rust Bridge" events.

So to start the name hunt. Playing with the words related to [bridge](http://www.thesaurus.com/browse/bridge):

* Rust Arch
* Rust Overpass
* Rust Trestle
* Rust Wing
* Rust Meld
* Rust Span (would be confusing for rustc developers 😄)
* Aboard Rust
* Rust Junction
* Rust Passage

Anyone have any better ideas?

**Comment by steveklabnik** [comment]
At the same time, the generic teaching "Foo Bridge" org is very, very well known, and far more than that project.

**Comment by Manishearth** [comment]
It's called neon now?

**Comment by Manishearth** [comment]
Oh, the bridge org name still exists. hm.

**Comment by aturon** [comment]
FWIW, when the new RustBridge effort was proposed I reached out to @dherman and @wycats and both thought it was fine to have both names -- that there wasn't much risk of confusion. (And, in fact, the two projects could align well).

I think, if we are trying to work within http://bridgefoundry.org/ (which seems ideal), we should stick with the RustBridge name.

**Comment by erickt** [comment]
@steveklabnik: that's true. We might be able to get @dherman to rename their parent project since their branding is more in the neon and helix project.

@Manishearth: neon is the JavaScript binding.

**Comment by erickt** [comment]
@aturon: That's great to hear. There could definitely be alignment at a high level, but we ought to make sure we avoid any other sources of confusion. For example, it looks like @dherman reserved http://rustbridge.io, but it doesn't have any content on it yet. I'm guessing @dherman was planning on having developer-oriented documentation on how to write good language bridging libraries, whereas I would expect our project would be optimized towards educating and engaging underrepresented communities, like [RailsBridge](http://railsbridge.org/) and [GoBridge](http://golangbridge.org/).

So either we could try to mash our front pages together somehow, which might work if we do it well, or we could have a separate rustbridge.org, but I'd worry about that being confusing.

**Comment by broesamle** [comment]
actually, the 'bridge' can serve as a connecting metaphor:
bridging technologies and bridging concepts between domains (technical or knowledge-wise) emphasises the similarities between both projects.




Martin Br:osamle     m-broe.de

-------- Ursprüngliche Nachricht --------
Von: Erick Tryzelaar <notifications@github.com> 
Datum: 20.05.2016  18:09  (GMT+01:00) 
An: rust-community/rustbridge <rustbridge@noreply.github.com> 
Betreff: Re: [rust-community/rustbridge] Unfortunate name collision with another RustBridge-named project (#4) 
 
@aturon: That's great to hear. There could definitely be alignment at a high level, but we ought to make sure we avoid any other sources of confusion. For example, it looks like @dherman reserved http://rustbridge.io, but it doesn't have any content on it yet. I'm guessing @dherman was planning on having developer-oriented documentation on how to write good language bridging libraries, whereas I would expect our project would be optimized towards educating and engaging underrepresented communities, like RailsBridge and GoBridge.

So either we could try to mash our front pages together somehow, which might work if we do it well, or we could have a separate rustbridge.org, but I'd worry about that being confusing.

**Comment by skade** [comment]
In any case, I was the one bringing that term into play last september an before in the sense that we are talking about here. I'd be quite sad if we move off here because someone else grabbed the name.

**Comment by softprops** [comment]
If we can't convince the owner of that github org to change names for the greater good, does rustlang bridge add any additional ambiguity/confusion.

**Comment by skade** [comment]
@softprops the owner of the repos are the head of mozilla research and a member of the core team, so I'd guess we won't have a problem on finding an agreement, especially as both have indicated to find a way.

I am, for the record, pretty much on the side that neon and helix are important projects for newcomers and beginners and do believe that a RustBridge must think beyond pure beginner-beginner-things[1], so I also don't believe that there's a huge problem in carrying both kinds of projects under the same name.

Also, carrying projects where people can work on and work with under the name of a Bridge is a _new_ thing, but I also think it's a _good_ thing if done right.

[1] Rust _is_ a secondary language pretty often, even in project structure.

**Comment by dherman** [comment]
I totally agree that these projects can coexist under the same terminology, and perhaps even join forces at some point! I agree with @skade -- I suspect there's real overlap in what we're trying to do, and maybe even collaboration opportunities. My hope has been that building an ecosystem of platform bridges to Rust will serve to connect communities and create opportunities, which IMO builds on Rust's potential as an enabling technology. (I mean, I *also* think this is going to be valuable for Rust adoption, but these goals are complementary.)

For the time being, the github/rustbridge projects are really just early-stage projects, so we don't have a lot of messaging or web presence. But I'm happy to collaborate if and when you think it makes sense.

**Comment by skade** [comment]
I think this can be closed. We will approach @dherman and the others on this.
