### ISSUE TITLE
RustBridge@Rustfest: Introduction Session (10 minutes)

### ISSUE THREAD

**Issue by aepsil0n** [rust-community/rustbridge#44]
## RustBridge
- Give people access to technology -- predominantly to goups under-represented in IT.
- Positive first contact hands-on experience
- Coaches...they are here to support you!
- This is a first test run of RustBridge. Thank you for being a part of this! We appreciate your feedback.
## Code of Conduct
- Open to everyone!
- Supportive!
- If you are unsure about anything, do not hesitate to ask!
- Try to help your co-learners!
## What to learn?
- Make a first contact with an amazing technology!
- Programming: 
  - Telling a machine (a piece of silicium and metal ...) what to do.
  - This will be small steps, at first.
- Predefined Examples that you can build your experience ontop!
## Learning Materials 

For different levels of prior experience
- [InstallFest: Get your machine ready for coding](https://github.com/rust-community/rustbridge/blob/master/workshops/installfest/user-guide.md)
- [Mondrian Pattern Generator:](https://github.com/rust-community/rustbridge/tree/master/workshops/mondrian-pattern) abstract painting and parallel computing
- [URL shortener:](https://github.com/rust-community/rustbridge/tree/master/workshops/url_shortener) how to design and build a Rust project
- [Text adventure:](https://github.com/rust-community/rustbridge/tree/master/workshops/textadventure) make a text-based adventure game

**Comment by aepsil0n** [comment]
cc @broesamle @johannhof

**Comment by aepsil0n** [comment]
Anybody started doing this? If not, I will do so tomorrow.

**Comment by johannhof** [comment]
Since I'm super busy with RustFest it'd be great if you could start, I'd be happy to give feedback or help decide if you're unsure about anything.

**Comment by broesamle** [comment]
when we are done with the toplevel comment we could actually integrate it as intro on the workshop toplevel page . . .
https://raw.githubusercontent.com/rust-community/rustbridge/master/workshops.md
