### ISSUE TITLE
Organize the first meeting of the RustBridge team

### ISSUE THREAD

**Issue by erickt** [rust-community/rustbridge#5]
Hello all!

We need to pick a day for the inaugural meeting of the RustBridge team. What days work best for you all to meet? I would like for us to try to meet next week (2016-06-05 through 2016-06-12), and I propose we host them on the #rust-community channel on irc.mozilla.org, just like the community team meeting. What days and times work best for you all? For me, I lean more to Tuesday at 9am PST, but I'm pretty flexible. How about the rest of you?

Agenda items:
- Pick a lead of the Bridge team that's responsible for driving the agenda and working with the community team / core team.
- Identify an approximate day for the first event.
- ???

**Comment by broesamle** [comment]
Who of you will join the [Berlin Rust Meetup](http://www.meetup.com/Rust-Berlin/events/231188250/) tomorrow? It would be a informal low-key-orga opportunity to get in touch with at least some of us...

**Comment by skade** [comment]
Me and @johannhof will certainly be there, @SonjaHeinen is out of town, but maybe @xamebax can join? :)

**Comment by Realtin** [comment]
I'm at the Clojure Meetup since there will be stuff to do for the ClojureBridge Workshop next Weekend
