### ISSUE TITLE
RustFest: Agree on final program

### ISSUE THREAD

**Issue by broesamle** [rust-community/rustbridge#51]
The [techschool blog](http://discourse.opentechschool.org/t/rustbridge-workshop-sept-18th-berlin-together-with-rustfest/1849) suggests:

> Sunday, September 18th 2016
> from 11am
> ThoughtWorks Werkstatt Berlin
> Mülhauser Str. 6, 10405 Berlin 

Ben reported
> - 16 learners with prior coding experience
> - 2 without prior coding experience (minimum rails girls weekend)
> - 4 more coaches
on monday, 12/9 thats quite an exciting number already!
 
@aepsil0n, I know we had thought of a two stage thing where we can rund 2x2 or even 2x3 workshops but it sounds plausible to me also, if we start as suggested at 11, give a quick overview about the workshops available and assign people to suitable groups/mentors. 

Workshops may need some oral instruction also (at least I would find it useful for the absolute beginners to give maybe 10 mins of intro before getting them lost **and impatient** in their machines). 

We should meet with the mentors a bit ahead in order to familarise them with the materials/program.

TODOs:
- [ ] Slides for the intro #44  !!!
- [ ] Internet, Electricity, Coffee, Snacks  
- [ ] Projector
- [ ] Printout of install cheat sheets (to be extracted from installfest docs) (Helpful but not prio 1 since most of the applicants have experiences already)

Rock'nRoll!

/M

**Comment by johannhof** [comment]
Updated the location to not have anyone confused.

**Comment by johannhof** [comment]
> Internet, Electricity, Coffee, Snacks
> Projector

@aepsil0n: Is this going to work or is there anything you need help with?

> Printout of install cheat sheets

Is that really necessary? People will have internet, I assume. If you really think we need it I can print them.

I'd suggest we meet with mentors at around 9-9:30 since we haven't had the time to meet in person before and we should go through the workshop. What's the best way to announce this to mentors?

I'll be the responsible contact person from the RustFest team for anything that comes up (e.g. CoC, transportation)

**Comment by aepsil0n** [comment]
@johannhof Is it at Werkstatt now or at Co-Up? I'm confused.

If it is at Werkstatt, I will be there tomorrow and make sure. I don't see any problems with anything in the list. Coffee & snacks I need to check and maybe organize myself.

Let's meet in the morning. 9am sounds good. If it's at Werkstatt, I'll make sure to get a key tomorrow to let everybody in. (I need to cast my vote for the elections some time before that ^^)

**Comment by johannhof** [comment]
@aepsil0n Werkstatt.

> Coffee & snacks I need to check and maybe organize myself.

We were not planning to deliver food to the workshops afaik but we can reimburse you for anything like coffee that you need to get for the workshop.

> (I need to cast my vote for the elections some time before that ^^)

Me too :smile:

**Comment by broesamle** [comment]
sounds like location and infrastructure is all sorted :) yeah!

**Comment by aepsil0n** [comment]
Alright snacks & coffee is accounted for. The rest is not an issue. Franziska will let us in Sunday at 9am. I'll make sure to be there on time.
