### ISSUE TITLE
mondrian workshop: main doesn't open piston window on macOS

### ISSUE THREAD

**Issue by tryge** [rust-community/rustbridge#56]
The issue seems to be that the `PistonWindow` needs to be created in the main thread on macOS.

The attached diff should fix the issue for macOS.

<img width="1703" alt="diff-serverthread-changes" src="https://cloud.githubusercontent.com/assets/106314/18614974/03d5e294-7d9a-11e6-8b45-ea736b03ad5e.png">

[changes.txt](https://github.com/rust-community/rustbridge/files/478636/changes.txt)

**Comment by broesamle** [comment]
thanks for the live-fixing the workshop!!
