### ISSUE TITLE
 Informal `RustBridge` chat at Berlin, 2016-06-08

### ISSUE THREAD

**Issue by broesamle** [rust-community/rustbridge#6]
Hi folks,
at the side of the [rust meet-up in Berlin](http://www.meetup.com/de-DE/Rust-Berlin/events/231188250/) on Wednesday
a couple of people discussed topics regarding beginners and advanced workshop materials. I will try to outline the key points:

* Most importantly, we agreed that the best of rust should come out in (each of) the tutorials one way or the other.

* Regarding the former point: Following other platforms established road by introducing their capabilities in setting up a basic web application would provoke the obvious question to ask would be: Why didn't we use Ruby or Python?

* So, it looks like we need something more rusty.

## Levels of experience

We stressed that there would be different levels of general beginners and advanced programmers to be addressed in terms of different courses/tutorials.

* Beginners-beginners might even struggle to use a text editor or have any idea about the precision required for expressing /idealised) things in formal ways, such as some (programming)language used to express a calculation process.

* For beginners, rusts elegance might not be experienced at first. How do you get excited about multi-threading without having encountered the restrictions of a sequential approach to calculation? In fact, this is part of what makes programming so hard to learn: Control or even restrict your human, parallel way of thinking into something strictly sequentially defined.

* An experienced programmer, by contrast, is aware of the more abstract requirements put on elegant and useful languages in a systems context.

* To teach beginners, Florian and I briefly discussed how to find graspable everyday things/concepts which would line up with some of the concepts that make rust so special (to us).

## Possible projects

* A game would be great!

* Something graphical would be great

* 'The system' is what rust is really good at. That hints at embedded things, easy-to-use flashable micro controlers; @skade 

* A chat bot should not be too complicated and could probably also be done with beginners

* Rudimentary multi-agent framework gives the opportunity to just change one agent and gradually expand your boundary of how much code you touch

**Comment by aepsil0n** [comment]
Great work!
@skade made me aware of RustBridge yesterday and I'd very much like to help out!

A quick thought about possible projects, in particular concerning games/something graphical. I have been working on a simple library for 2D graphics based on reactive programming, which is pretty close to the Elm architecture. @miosta and I paired on a [small prototype](https://github.com/miosta/pacgirl) showcasing this. This may be suitable for beginners, as it does not force you to think about all the OpenGL and windowing details right from the start.

**Comment by skade** [comment]
We agreed yesterday that providing a framework to embed the work in is probably good, as long as the framework is rather seamless and stable.

**Comment by aepsil0n** [comment]
Makes sense. Stability is still a bit of a tricky requirement in the Rust GameDev ecosystem. But as long as you depend on a fixed version, nothing breaks ;)

**Comment by skade** [comment]
Also see https://github.com/rust-community/team/issues/11

**Comment by erickt** [comment]
This happened!
