### ISSUE TITLE
License for materials in this repo?

### ISSUE THREAD

**Issue by carols10cents** [rust-community/rustbridge#69]
Hiiii so I'd like to add the material we used at the Pittsburgh Rustbridge, but I just noticed that we don't have a license for anything in this repo :( :( :(

We used slides that we modified starting from [slides of Ashley's that she's licensed MIT](https://github.com/ashleygwilliams/a-very-brief-intro-to-rust/blob/gh-pages/LICENSE), sooo I was trying to check that the license here was compatible with MIT.

[Railsbridge has licensed their docs as CC-BY and their code MIT](https://github.com/railsbridge/docs/blob/master/LICENSE.md).

## Proposal 

If it was totally up to me, I think doing what Railsbridge did makes sense, just say "any non-code text is CC-BY, any code is MIT". IANAL, but I think that would be compatible with the licensing that @ashleygwilliams has, at least in spirit. Do you have any objections to this proposal, Ashley?

If I don't hear from anyone by Nov 30, I'm going to do what I've proposed. If we come to a consensus before then, I'll take care of whatever we decide before then. But I don't want to add any more content until we decide, sorry for not noticing this earlier :(

**Comment by ashleygwilliams** [comment]
i am ok with this! sounds good!

**Comment by carols10cents** [comment]
Closing in favor of #39, which i totally missed. I'm glad I got your approval though @ashleygwilliams !
