### ISSUE TITLE
2016-06-22 @ 4pm UTC RustBridge Meeting

### ISSUE THREAD

**Issue by erickt** [rust-community/rustbridge#7]
Lets do this! Meeting is at 4pm UTC. Check this [link](http://everytimezone.com/#2016-6-2,1680,cn3) for your local timezone.

 Agenda items:

* Future meetings
* Team roles
* Start the [bridge tutorial](http://bridgefoundry.org/doc/bridge-building.html)
* Identify workshop topics
* Starting outreach to help get discounts and etc for upcoming meetups

**Comment by skade** [comment]
cc @rust-community/rustbridge who would be able to attend on that date?

**Comment by anoukruhaak** [comment]
Happy to be part of this meeting, but still in Amsterdam. Any chance I could join online? If not that's fine too, thought I'd at least ask ;)

**Comment by skade** [comment]
@anoukruhaak It's online only. IRC or $hangoutlike, what people prefer.

**Comment by hannelita** [comment]
I dont think I can make, I'll be in a flight :( Sorry!

**Comment by Realtin** [comment]
Wednesdays are always problematic for me unfortunately. Because that clashes with the ClojureBridge Learners Group. And this will be the Wednesday after our big workshop, so a lot of more learners will be expected. But I try to have an eye on the irc from time to time.

**Comment by broesamle** [comment]
let me see, there will be a few constraints I cannot influence, otherwise the day is flexible for me. Are we already settled on 4pm?

**Comment by aepsil0n** [comment]
I think I have time for that.

**Comment by skade** [comment]
Preferably, I'd stick to the time.

Please note that one part of this is "let's get this on the road" and hand out some work packages, finding a good time to meet is certainly one of them :).

**Comment by erickt** [comment]
I'm sorry this time doesn't work for you all. If you can't attend, could you reply with times that would work better for the next meeting? We can pick a different meeting time on Wednesday.

**Comment by hannelita** [comment]
(I thought about sharing a doc and everybody could fill up the days + hours that are convenient to meet).
Here is the schedule that usually works for me (except for this week that I'll have a flight to catch) 

<img width="998" alt="screen shot 2016-06-20 at 1 05 39 pm" src="https://cloud.githubusercontent.com/assets/506426/16208537/8be9d4b4-36e7-11e6-8f72-9ee758ef9f85.png">

If you want,
https://docs.google.com/spreadsheets/d/1JJbkASQS4JxP5WDHLbnun4odlDpLA-a_z6F_s5Jpup8/edit?usp=sharing
You can concatenate your names into the cells. I can check the cells with more names and determine which are the most convenient meeting hours. 

Thanks!

**Comment by erickt** [comment]
Thanks Hanneli!

I added some of my availability to it. Note that the full community team
meeting alternates to meeting at 2am UTC and 4pm UTC, with tomorrow's
meeting at 2am. So if we pick this time, some of us may not be available
every other week.

-e

**Comment by skade** [comment]
@erickt can you provide a link to join it? I'd prefer some way of audio connection for the inaugural call.

**Comment by broesamle** [comment]
presumably I will be on the train during the meeting. what would you suggest as a channel to join?

**Comment by skade** [comment]
Well, Hangouts (mobile) usually works best (somewhat).

**Comment by aepsil0n** [comment]
So, the 4pm UTC slot is still going to happen? If so, who is setting up the meeting? Can that person send a link to it?

**Comment by erickt** [comment]
Hello everyone,

Yes the meeting is still on for 4pm UTC. I've created a [hangouts chat](https://plus.google.com/hangouts/_/calendar/YXBkOXZtYmMyMmVnZW5tdHU1bDZjNWpiZmNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ.27d1ptvtas57oia96vrt4bf2ek?authuser=1). You can also find it in the [community calendar](https://www.google.com/calendar/embed?src=apd9vmbc22egenmtu5l6c5jbfc@group.calendar.google.com). Note that I did advertise this meeting to be on the #rust-community IRC (except for on here, I'm sorry about that), so we might have some people show up from the broader community, so if that happens I'll redirect them to the hangout chat.

**Comment by skade** [comment]
Okay, I have to leave after ~20-25 minutes, because of an unplanned thing, but that should be enough to say my words :).

**Comment by erickt** [comment]
@rust-community/rustbridge: meeting starts in 7 minutes!

**Comment by skade** [comment]
@anoukruhaak ping

**Comment by skade** [comment]
@broesamle @aepsil0n ping

**Comment by carols10cents** [comment]
My schedule is irregular and flexible, so please pick a time that works for people with less flexible schedules and I will probably be able to make it :) I'm in EDT.

**Comment by broesamle** [comment]
still working on hangouts. ..its not set up on my phone obviously

**Comment by broesamle** [comment]
and refuses to get installed because i "have no devices" :P

**Comment by broesamle** [comment]
sorry, it doesn't look fixable for the moment. The account i am using is not matched with my phone by hangouts/Google

**Comment by erickt** [comment]
[Meeting minutes](https://github.com/rust-lang/meeting-minutes/blob/master/rustbridge/2016-06-22.txt)

@broesamle: I'm sorry it didn't work for you! We can do some testing next time, or hold the meeting on irc to make it easier to attend.
