### ISSUE TITLE
Rust newbie contributing to RustBridge

### ISSUE THREAD

**Issue by anna-liao** [rust-community/rustbridge#86]
I have been programming with Python for a few years, and became intrigued by systems programming languages such as Go and Rust, as I could tell how much it improved efficiency in a project.  I started reading up on each language and found it difficult to dive in.  Very excited that the Rust community is making it a goal to mentor and make it easier for newcomers to participate.  I would like to help out with RustBridge.  Let me know how I can help, without knowing much about the Rust language.

**Comment by sebasmagri** [comment]
Hi @anna-liao, and welcome! What's your main area of expertise?
Regards!

**Comment by anna-liao** [comment]
@sebasmagri I have used Python to put together IoT systems for remote sensor data collection and data analysis.

**Comment by sebasmagri** [comment]
@anna-liao I'd recommend to attend tomorrow's community meeting so we can discuss about collaboration opportunities on RustBridge :-) rust-community/team#174

**Comment by anna-liao** [comment]
@sebasmagri Thanks! I plan on attending the meeting today

**Comment by skade** [comment]
@anna-liao Hi, have you found something to work on? Could you please close this issue if you did, otherwise, well keep it open to continue finding something for you. Welcome again and thanks :).

**Comment by anna-liao** [comment]
@skade I have found something to work on and know when to attend the community meetings, so I will close this issue.  Thanks for the reminder!
