### ISSUE TITLE
Submitting edit suggestions to RustBridge tutorial website

### ISSUE THREAD

**Issue by anna-liao** [rust-community/rustbridge#88]
Hello,

What is the procedure to submit edit suggestions to the RustBridge tutorial website material? https://community.rs/rustbridge/beginners/tutorial-text.html

There are a few changes I would like to point out.  Not sure if each change should be a different commit?

Thanks,
Anna

**Comment by badboy** [comment]
You can bundle smaller changes in related commits (e.g. typos, small word changes).
For bigger rewordings, reformatting, etc. a commit per change is a good idea.

**Comment by skade** [comment]
In general, I subscribe to the notion that you shouldn't get ceremony in the way of a good change. Making sure things stay manageable for all sides by using @badboy's recommendations helps, but we are very used to many different working styles and can review them in any case.

**Comment by anna-liao** [comment]
@ashleygwilliams mentioned in Jul12 community team mtg that RustBridge workshop materials are mostly from here: https://github.com/ashleygwilliams/rust-emergency-compliment
So for now, I won't submit edits to this book material.
