### ISSUE TITLE
RustBridge Hyderabad

### ISSUE THREAD

**Issue by ranjithrajv** [rust-community/rustbridge#93]
Dates: November 2, 3, 2018
Venue: Mahindra École Centrale, Hyderabad(Zero charges for Venue)
Participation count: Around 500+ students

Projector: Available
Internet Connection: Available
Electricity (multiplier cables): Available

Support Needed:
* Mentors/Speakers
* Budget
* Swag

**Comment by ghost** [comment]
@ranjithrajv Please open this as an issue (with the same issue text) at http://github.com/rustbridge/team/issues. Thanks!
